### ISSUE TITLE
Active?

### ISSUE THREAD

**Issue by lmiller1990** [ktsn/vue-canvas#3]
Is this active? I am interested in making some simple canvas based 2d games using Vue. 

Will clone and repo and take a look this week! Just checking up on the status of dev.

**Comment by ktsn** [comment]
Sorry, this is not active because I have no project for using this lib, currently.
You can see the current implementation status in #2

**Comment by lmiller1990** [comment]
Sure. I might try it out anyway. Thanks for replying. Do you have any recommendations for Vue apps that will use <canvas> a lot?

**Comment by ktsn** [comment]
Hmm, I have no idea about that. I always wrap a canvas by Vue component and write a brief adapter.
